development:
  adapter: postgresql
  database: DaK_development
  pool: 5
  timeout: 5000
  username: fenix
  password:

test:
  adapter: postgresql
  database: DaK_test
  pool: 5
  timeout: 5000
  username: fenix
  password:
